api/urls.py
from django.urls import path
from api.views import recipes_api , recipe,  categories_api, category , SubscriberCreateAPIView
from api.routers import router

urlpatterns = [
    path('recipes/', recipes_api , name = 'recipes'),
    path('recipes/<int:id>/', recipe, name='api_recipe'),
    # path('stories/', stories_api , name = 'stories'),
    # path('stories/<int:id>/', story, name='api_story'),
    # path('stories/?categories=<slug:str>/', story_for_category, name='story_for_category'),
    path('categories/', categories_api , name = 'categories'),
    path('categories/<int:id>/', category, name='api_categories'),
    path('subscribe/', SubscriberCreateAPIView.as_view(), name='subscribe'),
    
] + router.urls

food_stories/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

 

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace='stories')),
    path('user/', include('accounts.urls',namespace='user')),
    path('api/v1.0/', include('api.urls') ),
    path('api/v1.0/auth/', include('accounts.api.urls', namespace='api_account')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path
from stories.views import HomePage , about ,StoryListView , RecipeListView , StoryDetailView , RecipeDetailView , ContactView, \
    CreateStoryView , StoryUpdateView , StoryDeleteView , CreateRecipeView , RecipeUpdateView , RecipeDeleteView , SaveRecipeView, \
    SavedRecipeListView , export_excel_view , SubscriberCreateView


app_name = 'stories'
urlpatterns = [
    path('', HomePage.as_view(), name = 'home'),
    path('about/', about , name = 'about'),
    path('recipes/', RecipeListView.as_view() , name = 'recipes'),
    path('recipes/<str:slug>', RecipeDetailView.as_view(), name='recipe_detail'),
    path('stories/', StoryListView.as_view() , name = 'stories'),
    path('stories/<str:slug>/', StoryDetailView.as_view(), name='story_detail'),
    path('contact/', ContactView.as_view() , name = 'contact'),
    path('create-story',CreateStoryView.as_view(), name = 'create_story'),
    path('create-recipe',CreateRecipeView.as_view(), name = 'create_recipe'),
    path('update-story/<str:slug>/', StoryUpdateView.as_view(), name = 'update_story') ,
    path('delete-story/<str:slug>/', StoryDeleteView.as_view(), name = 'delete_story') ,
    path('update-recipe/<str:slug>/', RecipeUpdateView.as_view(), name = 'update_recipe') ,
    path('delete-recipe/<str:slug>/', RecipeDeleteView.as_view(), name = 'delete_recipe') ,
    path('save-recipe/<int:pk>/', SaveRecipeView.as_view(), name = 'save_recipe') ,
    path('saved-recipes/', SavedRecipeListView.as_view(), name='saved_recipes'),
    path('export/',export_excel_view, name = 'export_excel_view' ),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),
]

stories/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from stories.tools.slug_generator import slugify
from datetime import datetime
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy
import math 

USER_MODEL = get_user_model()


class Category(models.Model):
    """
    Bu model reseptlerin ve storilerin kategoriyalarini saxlamaq ucundu.
    Misal: Deset, Yemek
    """

    #informations
    title = models.CharField('Title', max_length=120)
    image = models.ImageField('Image', upload_to='category_images')

    # moderations
    show_page = models.BooleanField(default=False)
    is_published = models.BooleanField('is published', default=True)
    order = models.PositiveIntegerField('Order', default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('order',)
    
    def __str__(self):
        return self.title


class Tag(models.Model):

    #information
    title = models.CharField('Title', max_length=40)

    # moderations
    is_published = models.BooleanField('is published', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tag'
    
    def __str__(self):
        return self.title


class Recipe(models.Model):
    # relations
    category = models.ForeignKey(Category, verbose_name='Kateqoriya', on_delete=models.CASCADE, db_index=True, related_name='recipes')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', related_name='recipes')
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, db_index=True, related_name='recipes')

    # informations
    title = models.CharField('Basligi', max_length=120)
    slug= models.SlugField('slug',max_length=255, editable = False , unique = True)
    short_description = models.CharField('Qisa Mezmunu', max_length=255, help_text='Bu sahe repestler siyahisinda reseptin mezmunu olaraq gorunur...')
    image = models.ImageField('Sekil', upload_to='recipes')
    long_description = RichTextField('Genis mezmunu')
    show_home_page = models.BooleanField(default=False)
    # author = models.CharField('Muellif', max_length=50)

    # moderations
    min_read_time = models.PositiveIntegerField('Min read time', editable=False, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField('is published', default=True)

    class Meta: # table name: stroies_recipe
        # app_label = 'story'
        # db_table = 'resept'
        verbose_name = 'Resept'
        verbose_name_plural = 'Reseptler'
        ordering = ('-created_at', '-title')

    def __str__(self):
        return f"{self.title} category: {self.category}"

    
    def save(self, *args, **kwargs):
        article_word_count = len(self.long_description.split(' '))
        self.min_read_time = math.ceil(article_word_count/120)
        if not self.slug:
            self.slug = f"{slugify(self.title)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('stories:recipe_detail', kwargs={'slug': self.slug })

class Story(models.Model):
    # relations
    category = models.ForeignKey(Category, verbose_name='Kateqoriya', on_delete=models.CASCADE, db_index=True, related_name='stories')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', related_name='stories')
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, db_index=True, related_name='stories')

    # informations
    
    title = models.CharField('Basligi', max_length=120)
    slug= models.SlugField('slug',max_length=255, editable = False , unique = True)
    image = models.ImageField('Sekil', upload_to='recipes')
    long_description = RichTextField('Genis mezmunu')
    show_home_page = models.BooleanField(default=False)
    # author = models.CharField('Muellif', max_length=50)

    # moderations
    min_read_time = models.PositiveIntegerField('Min read time', editable=False, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField('is published', default=True)

    class Meta: # table name: stroies_recipe
        # app_label = 'story'
        # db_table = 'resept'
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'
        ordering = ('-created_at', '-title')

    def __str__(self):
        return f"{self.title} category: {self.category}"

    def save(self, *args, **kwargs):
        article_word_count = len(self.long_description.split(' '))
        self.min_read_time = math.ceil(article_word_count/120)
        if not self.slug:
            self.slug = f"{slugify(self.title)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('stories:story_detail', kwargs={'slug': self.slug }) 


class Comment(models.Model):
    # relations
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    # story to do add story model and relation here
    user = models.ForeignKey(USER_MODEL, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    parent_comment = models.ForeignKey('self', related_name='child_comments', on_delete=models.CASCADE, null=True, blank=True)
    user_name = models.CharField('Name', max_length=50, null=True, blank=True)
    email = models.EmailField('Email', max_length=40, null=True, blank=True)
    # website = models.URLField('Website', null=True, blank=True)
    message = models.TextField('Message')

class Contact(models.Model):
    name = models.CharField('Name', max_length=40)
    email = models.EmailField('Email', max_length=40)
    subject = models.CharField('Subject', max_length=255)
    message = models.TextField('Message')

    # moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    def get_email(self):
        return self.email

    def __str__(self):
        return f"{self.name} subject: {self.subject}"

class SavedArticle(models.Model):
    user = models.ForeignKey(USER_MODEL, on_delete = models.CASCADE, related_name = 'saved_articles')
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE, related_name = 'recipe_saved_articles', null=True , blank = True)
    story = models.ForeignKey(Story, on_delete = models.CASCADE, related_name = 'story_saved_articles', null=True , blank = True)

     # moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Saved Article'
        verbose_name_plural = 'Saved Articles'

    def __str__(self):
        return f"{self.user} recipe: {self.recipe} story: {self.story} "

class Subscriber(models.Model):
    # information's
    email = models.EmailField('Email', max_length=30, unique=True)
    is_active = models.BooleanField('is active', default=True)

    # moderation's
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'

    def __str__(self):
        return self.email

stories/forms.py
from django import forms
from stories.models import Contact, Recipe, Story, Category, Tag , Subscriber
from ckeditor.widgets import CKEditorWidget 
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class StoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={
                    'class': 'form-control'
                }))
    tags =  forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={
                    'class': 'form-control',
                }) )
    class Meta:
        model = Story
        fields = ('title', 'category', 'tags', 'long_description', 'image',)
        widgets = {
            'title': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                }),
            'long_description': CKEditorUploadingWidget(),

        }

class RecipeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={
                    'class': 'form-control'
                }))
    tags =  forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={
                    'class': 'form-control',
                }) )
    class Meta:
        model = Recipe
        fields = ('title', 'category', 'tags', 'short_description', 'long_description', 'image',)
        widgets = {
            'title': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                }),
            'short_description': forms.Textarea(attrs={
                    'class': 'form-control',
                    'placeholder': 'Short Description',
                    'rows'  : '5',
                    'cols' : '20',
                }),
            'long_description': CKEditorUploadingWidget(),

        }

class ContactForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=13, initial='+994', min_length=7, widget=forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Phone Number',
                }), help_text='Sizinle elaqeye kecmeyimiz ucun nomre daxil etmeyiniz sertdir!')
    class Meta:
        model = Contact
        fields = (
            'name',
            'email',
            'subject',
            'phone_number',
            'message',
           
        )
        widgets = {
            'name': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Your name',
                }),
            'email': forms.EmailInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Your email',
                }),
            'subject': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Subject',
                }),
            'message': forms.Textarea(attrs={
                    'class': 'form-control',
                    'placeholder': 'Message',
                    'rows': 7,
                    'cols': 30,
                })
        }

    
    def clean(self):
        print('here')
        cleaned_data = super().clean()
        print(cleaned_data)

    # def clean_phone_number(self):
    #     phone_number = self.changed_data.get('phone_number')

class RecipeAdminForm(forms.ModelForm):
    long_description = forms.CharField(widget=CKEditorUploadingWidget())
    class Meta:
        model = Recipe
        fields = '__all__'

class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = (
            'email',
        )

        widgets = {
            'email': forms.EmailInput(attrs={
                'class':  'form-control',
                'placeholder': 'Enter email address',
            })
        }

stories/templates/about.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} About {% endblock %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'stories:home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image:url({% static 'images/about.jpg' %});"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>About Stories</span></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                            {% informations as information %}
                                <strong class="number" data-number="{{information.daily_visitors}}">0</strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="{{information.stories}}">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                            
                                <strong class="number" data-number="{{information.recipes}}">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="{{information.users}}">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock %}

stories/templates/recipes.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} Recipes {% endblock %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Recipes</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'stories:home' %}">Home <i
                                class="ion-ios-arrow-forward"></i></a></span> <span>Recipes <i
                            class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    {% for recipe in recipe_list %}
                    <div class="col-md-6 col-lg-12 ftco-animate">
                        <div class="blog-entry d-lg-flex">
                            <div class="half">
                                <a href="{% url 'stories:recipe_detail' recipe.slug %}" class="img d-flex align-items-end"
                                    style="background-image: url('{{recipe.image.url}}');">
                                    <div class="overlay"></div>
                                </a>
                            </div>
                            <div class="text px-md-4 px-lg-5 half pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{recipe.category.title}}</span><span class="ml-auto pl-3">{{recipe.created_at|date:"F d, Y"}}</span>
                                </p>
                                <h3><a href="{% url 'stories:recipe_detail' recipe.slug %}">{{recipe.title}}</a> <i onclick="save_article({{recipe.id}})" class="fa fa-heart" style="font-size:24px;color:red;margin-left:10px;cursor:pointer"></i></h3>
                                <p>{{recipe.short_description}}
                                </p>
                                <p class="mb-0"><a href="{% url 'stories:recipe_detail' recipe.slug %}"class="btn btn-primary">Read More <span
                                            class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h1>Gosterilecek melumat yoxdur</h1>
                    {% endfor %}

                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                {% endif %}
                               
                                {% for page in page_obj.paginator.page_range %}
                                {% if page == page_obj.number %}
                                <li class="active"><span>{{page}}</span></li>
                                {% else %}
                                <li><a href="?page={{page}}">{{page}}</a></li>
                                {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.paginator.num_pages }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="sidebar-wrap">
                   {% if request.user.is_authenticated %}
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="{{ request.user.get_avatar }}" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>{{request.user.bio}}</p>
                        </div>
                    </div>
                    {% endif %}
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box categories text-center ftco-animate">
                            <h2 class="heading mb-4">Categories</h2>
                            <ul class="category-image">
                                {% category as items %}
                                {% for category  in items %}
                                <li>
                                    <a href="{% url 'stories:stories' %}"
                                        class="img d-flex align-items-center justify-content-center text-center"
                                        style="background-image: url('{{category.image.url}}')">
                                        <div class="text">
                                            <h3>{{category.title}}</h3>
                                        </div>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>





{% endblock %}

{% block js %}
    <script>
    function save_article(recipe_id){
        $.ajax({
            url: "{% url 'stories:save_recipe' 12345 %}".replace('12345', recipe_id),
            method: 'GET',
            success: function(data){
                alert(data);
            }
        })
    }
    </script>

{% endblock %}

stories/templates/saved_recipes.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} Recipes {% endblock %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Saved Recipes</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'stories:home' %}">Home <i
                                class="ion-ios-arrow-forward"></i></a></span> <span>Recipes <i
                            class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    {% for recipe in recipe_list %}
                    <div class="col-md-6 col-lg-12 ftco-animate">
                        <div class="blog-entry d-lg-flex">
                            <div class="half">
                                <a href="{% url 'stories:recipe_detail' recipe.slug %}" class="img d-flex align-items-end"
                                    style="background-image: url('{{recipe.image.url}}');">
                                    <div class="overlay"></div>
                                </a>
                            </div>
                            <div class="text px-md-4 px-lg-5 half pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{recipe.category.title}}</span><span class="ml-auto pl-3">{{recipe.created_at|date:"F d, Y"}}</span>
                                </p>
                                <h3><a href="{% url 'stories:recipe_detail' recipe.slug %}">{{recipe.title}}</a> <i onclick="save_article({{recipe.id}})" class="fa fa-heart" style="font-size:24px;color:red;margin-left:10px;cursor:pointer"></i></h3>
                                <p>{{recipe.short_description}}
                                </p>
                                <p class="mb-0"><a href="{% url 'stories:recipe_detail' recipe.slug %}"class="btn btn-primary">Read More <span
                                            class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h1>Gosterilecek melumat yoxdur</h1>
                    {% endfor %}

                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                {% endif %}
                               
                                {% for page in page_obj.paginator.page_range %}
                                {% if page == page_obj.number %}
                                <li class="active"><span>{{page}}</span></li>
                                {% else %}
                                <li><a href="?page={{page}}">{{page}}</a></li>
                                {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.paginator.num_pages }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="sidebar-wrap">
                   {% if request.user.is_authenticated %}
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="{{ request.user.get_avatar }}" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>{{request.user.bio}}</p>
                        </div>
                    </div>
                    {% endif %}
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box categories text-center ftco-animate">
                            <h2 class="heading mb-4">Categories</h2>
                            <ul class="category-image">
                                {% category as items %}
                                {% for category  in items %}
                                <li>
                                    <a href="{% url 'stories:stories' %}"
                                        class="img d-flex align-items-center justify-content-center text-center"
                                        style="background-image: url('{{category.image.url}}')">
                                        <div class="text">
                                            <h3>{{category.title}}</h3>
                                        </div>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>





{% endblock %}