accounts/api/urls.py
from django.urls import path
from accounts.api.views import register , CustomAuthToken
# from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api_account'
urlpatterns = [
    path('register/',register, name='register'),
    path('login/',CustomAuthToken.as_view(), name='login'),
]

accounts/urls.py
from django.urls import path , re_path
from accounts.views import UserProfile , CreateRegisterView , RegisterUpdateView , CustomLoginView , activate ,\
    CustomPasswordChangeView , ForgetPasswordView , CustomPasswordResetConfirmView
from django.contrib.auth.views import LogoutView

# app_name = "accounts"

app_name = 'user'
urlpatterns = [
    path('user-profile/',UserProfile.as_view(),name = 'user_profile'),
    path('register/', CreateRegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    re_path(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activation'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit_profile/<str:slug>', RegisterUpdateView.as_view(), name='edit_profile'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('forget-password/', ForgetPasswordView.as_view(), name='forget_password'),
    re_path(r'password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

api/urls.py
from django.urls import path
from api.views import recipes_api , recipe,  categories_api, category , SubscriberCreateAPIView
from api.routers import router

urlpatterns = [
    path('recipes/', recipes_api , name = 'recipes'),
    path('recipes/<int:id>/', recipe, name='api_recipe'),
    # path('stories/', stories_api , name = 'stories'),
    # path('stories/<int:id>/', story, name='api_story'),
    # path('stories/?categories=<slug:str>/', story_for_category, name='story_for_category'),
    path('categories/', categories_api , name = 'categories'),
    path('categories/<int:id>/', category, name='api_categories'),
    path('subscribe/', SubscriberCreateAPIView.as_view(), name='subscribe'),
    
] + router.urls

food_stories/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

 

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace='stories')),
    path('user/', include('accounts.urls',namespace='user')),
    path('api/v1.0/', include('api.urls') ),
    path('api/v1.0/auth/', include('accounts.api.urls', namespace='api_account')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path
from stories.views import HomePage , about ,StoryListView , RecipeListView , StoryDetailView , RecipeDetailView , ContactView, \
    CreateStoryView , StoryUpdateView , StoryDeleteView , CreateRecipeView , RecipeUpdateView , RecipeDeleteView , SaveRecipeView, \
    SavedRecipeListView , export_excel_view , SubscriberCreateView


app_name = 'stories'
urlpatterns = [
    path('', HomePage.as_view(), name = 'home'),
    path('about/', about , name = 'about'),
    path('recipes/', RecipeListView.as_view() , name = 'recipes'),
    path('recipes/<str:slug>', RecipeDetailView.as_view(), name='recipe_detail'),
    path('stories/', StoryListView.as_view() , name = 'stories'),
    path('stories/<str:slug>/', StoryDetailView.as_view(), name='story_detail'),
    path('contact/', ContactView.as_view() , name = 'contact'),
    path('create-story',CreateStoryView.as_view(), name = 'create_story'),
    path('create-recipe',CreateRecipeView.as_view(), name = 'create_recipe'),
    path('update-story/<str:slug>/', StoryUpdateView.as_view(), name = 'update_story') ,
    path('delete-story/<str:slug>/', StoryDeleteView.as_view(), name = 'delete_story') ,
    path('update-recipe/<str:slug>/', RecipeUpdateView.as_view(), name = 'update_recipe') ,
    path('delete-recipe/<str:slug>/', RecipeDeleteView.as_view(), name = 'delete_recipe') ,
    path('save-recipe/<int:pk>/', SaveRecipeView.as_view(), name = 'save_recipe') ,
    path('saved-recipes/', SavedRecipeListView.as_view(), name='saved_recipes'),
    path('export/',export_excel_view, name = 'export_excel_view' ),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from stories.tools.slug_generator import slugify
from django.urls import reverse_lazy
from datetime import datetime
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    image = models.ImageField(upload_to='user_images', null=True, blank=True)
    bio = models.TextField(_('Biography'), null=True, blank=True)
    slug= models.SlugField('slug',max_length=255, editable = False , unique = True)


    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def get_avatar(self):
        if self.image:
            return self.image.url
        return 'https://cdt.org/files/2015/10/2015-10-06-FB-person.png'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = f"{slugify(self.username)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('stories:home')

    @property
    def is_author(self):
        return self.groups.filter(name='Author').exists()


# Create your models here.

stories/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from stories.tools.slug_generator import slugify
from datetime import datetime
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy
import math 

USER_MODEL = get_user_model()


class Category(models.Model):
    """
    Bu model reseptlerin ve storilerin kategoriyalarini saxlamaq ucundu.
    Misal: Deset, Yemek
    """

    #informations
    title = models.CharField('Title', max_length=120)
    image = models.ImageField('Image', upload_to='category_images')

    # moderations
    show_page = models.BooleanField(default=False)
    is_published = models.BooleanField('is published', default=True)
    order = models.PositiveIntegerField('Order', default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('order',)
    
    def __str__(self):
        return self.title


class Tag(models.Model):

    #information
    title = models.CharField('Title', max_length=40)

    # moderations
    is_published = models.BooleanField('is published', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tag'
    
    def __str__(self):
        return self.title


class Recipe(models.Model):
    # relations
    category = models.ForeignKey(Category, verbose_name='Kateqoriya', on_delete=models.CASCADE, db_index=True, related_name='recipes')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', related_name='recipes')
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, db_index=True, related_name='recipes')

    # informations
    title = models.CharField('Basligi', max_length=120)
    slug= models.SlugField('slug',max_length=255, editable = False , unique = True)
    short_description = models.CharField('Qisa Mezmunu', max_length=255, help_text='Bu sahe repestler siyahisinda reseptin mezmunu olaraq gorunur...')
    image = models.ImageField('Sekil', upload_to='recipes')
    long_description = RichTextField('Genis mezmunu')
    show_home_page = models.BooleanField(default=False)
    # author = models.CharField('Muellif', max_length=50)

    # moderations
    min_read_time = models.PositiveIntegerField('Min read time', editable=False, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField('is published', default=True)

    class Meta: # table name: stroies_recipe
        # app_label = 'story'
        # db_table = 'resept'
        verbose_name = 'Resept'
        verbose_name_plural = 'Reseptler'
        ordering = ('-created_at', '-title')

    def __str__(self):
        return f"{self.title} category: {self.category}"

    
    def save(self, *args, **kwargs):
        article_word_count = len(self.long_description.split(' '))
        self.min_read_time = math.ceil(article_word_count/120)
        if not self.slug:
            self.slug = f"{slugify(self.title)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('stories:recipe_detail', kwargs={'slug': self.slug })

class Story(models.Model):
    # relations
    category = models.ForeignKey(Category, verbose_name='Kateqoriya', on_delete=models.CASCADE, db_index=True, related_name='stories')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', related_name='stories')
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, db_index=True, related_name='stories')

    # informations
    
    title = models.CharField('Basligi', max_length=120)
    slug= models.SlugField('slug',max_length=255, editable = False , unique = True)
    image = models.ImageField('Sekil', upload_to='recipes')
    long_description = RichTextField('Genis mezmunu')
    show_home_page = models.BooleanField(default=False)
    # author = models.CharField('Muellif', max_length=50)

    # moderations
    min_read_time = models.PositiveIntegerField('Min read time', editable=False, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField('is published', default=True)

    class Meta: # table name: stroies_recipe
        # app_label = 'story'
        # db_table = 'resept'
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'
        ordering = ('-created_at', '-title')

    def __str__(self):
        return f"{self.title} category: {self.category}"

    def save(self, *args, **kwargs):
        article_word_count = len(self.long_description.split(' '))
        self.min_read_time = math.ceil(article_word_count/120)
        if not self.slug:
            self.slug = f"{slugify(self.title)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('stories:story_detail', kwargs={'slug': self.slug }) 


class Comment(models.Model):
    # relations
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    # story to do add story model and relation here
    user = models.ForeignKey(USER_MODEL, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    parent_comment = models.ForeignKey('self', related_name='child_comments', on_delete=models.CASCADE, null=True, blank=True)
    user_name = models.CharField('Name', max_length=50, null=True, blank=True)
    email = models.EmailField('Email', max_length=40, null=True, blank=True)
    # website = models.URLField('Website', null=True, blank=True)
    message = models.TextField('Message')

class Contact(models.Model):
    name = models.CharField('Name', max_length=40)
    email = models.EmailField('Email', max_length=40)
    subject = models.CharField('Subject', max_length=255)
    message = models.TextField('Message')

    # moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    def get_email(self):
        return self.email

    def __str__(self):
        return f"{self.name} subject: {self.subject}"

class SavedArticle(models.Model):
    user = models.ForeignKey(USER_MODEL, on_delete = models.CASCADE, related_name = 'saved_articles')
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE, related_name = 'recipe_saved_articles', null=True , blank = True)
    story = models.ForeignKey(Story, on_delete = models.CASCADE, related_name = 'story_saved_articles', null=True , blank = True)

     # moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Saved Article'
        verbose_name_plural = 'Saved Articles'

    def __str__(self):
        return f"{self.user} recipe: {self.recipe} story: {self.story} "

class Subscriber(models.Model):
    # information's
    email = models.EmailField('Email', max_length=30, unique=True)
    is_active = models.BooleanField('is active', default=True)

    # moderation's
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'

    def __str__(self):
        return self.email

accounts/api/views.py
from rest_framework.decorators import api_view
from accounts.api.serializers import RegisterSerializer , UserProfileSerializer , LoginSerializer
from rest_framework.response import Response
from rest_framework.status import HTTP_201_CREATED, HTTP_200_OK
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.generics import GenericAPIView 

@api_view(('POST',))
def register(request):
    user_data = request.data
    serializer = RegisterSerializer(data=user_data)
    serializer.is_valid(raise_exception=True)
    serializer.save()
    return Response(serializer.data, status=HTTP_201_CREATED)



class CustomAuthToken(GenericAPIView):
    serializer_class = LoginSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.user
        user_serializer = UserProfileSerializer(user)
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'user_detail' : user_serializer.data
        })

accounts/templates/change_password.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} Change Password {% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
    <div class="container">
        <div class="row block-9 justify-content-center">
            <div class="col-md-6 order-md-last d-flex">
                <form action="" method="POST" class="bg-light p-5 contact-form">
                    <div class="form-group">
                        <h4 class="reset center">Change your password</h4>
                        <h6 class="center">Please choose a new password to finish signing in.</h6>
                    </div>
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        {{field}}
                        {{field.help_text}}
                        {{field.errors}}
                    </div>
                    {% endfor %}
                    <div class="form-group center">
                        <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} Edit-Profile {% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_errors }}
                        {% for field in form %}
                        <div class="form-group">
                            {{field}}
                            {{field.help_text}}
                            {{field.errors}}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <input type="submit" value="Edit Profile" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/forget_password.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} Forget Password {% endblock %}

{% block content %}
 <section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        {{field}}
                        {{field.help_text}}
                        {{field.errors}}
                    </div>
                    {% endfor %}
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load static custom_tags socialaccount %}
{% block title %} Sign In {% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
    <div class="container">
        <div class="row block-9 justify-content-center">
            <div class="col-md-6 order-md-last d-flex">
                <form action="" method="POST" class="bg-light p-5 contact-form">
                    <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        {{field}}
                        {{field.help_text}}
                        {{field.errors}}
                    </div>
                    {% endfor %}


                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                        <a href="{% url 'user:forget_password' %}" class="forgot-password">Forgot password?</a>
                    </div>
                    <div class="form-group">
                        <a href="{% url 'user:register' %}" class="">Don't have an account? Sign up</a>
                    </div>
                    <div class="form-group center">
                        <a href="{% provider_login_url "facebook" method="oauth2" %}" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                        <a href="{% provider_login_url "google" %} " class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} Sign Up {% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_errors }}
                        {% for field in form %}
                        <div class="form-group">
                            {{field}}
                            {{field.help_text}}
                            {{field.errors}}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/reset_password.html
{% extends 'base.html' %}
{% load static custom_tags i18n %}
{% block title %} Reset Password {% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
    <div class="container">
        <div class="row block-9 justify-content-center">
            <div class="col-md-6 order-md-last d-flex">
                <form action="" method="POST" class="bg-light p-5 contact-form">
                    {% if validlink %}
                    <div class="form-group">
                        <h4 class="reset center">Reset your password</h4>
                        <h6 class="center">Please choose a new password to finish signing in.</h6>
                    </div>
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    <div class="form-group">
                        {{field}}
                        {{field.help_text}}
                        {{field.errors}}
                    </div>
                    {% endfor %}
                    <div class="form-group center">
                        <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                    </div>
                    {% else %}
                    <h6 class="center">
                        {% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}
                    </h6>

                    {% endif %}

                </form>

            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/user-profile.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block title %} User-Profile {% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
<section class="ftco-section ftco-no-pt ">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="user-profile-side-bar sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="{{ request.user.get_avatar }}" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>{{request.user.bio}}</p>
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate user-profile">

                        <a href="{% url 'user:edit_profile' user.slug %}" class="btn btn-hover-color py-2">Edit Profile</a>

                    </div>
                    <div class="sidebar-box ftco-animate user-profile">

                        <a href="{% url 'user:change_password' %}" class="btn btn-hover-color py-2">Change Password</a>

                    </div>
                    {% if request.user.is_author %}
                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="{% url 'stories:create_story' %}" class="btn btn-hover-color py-2">Create story </a>
                    </div>
                    {#} {% if perms.stories.add_recipe %} #}
                    <div class="sidebar-box ftco-animate user-profile">
                        <a href="{% url 'stories:create_recipe' %}" class="btn btn-hover-color py-2">Create recipe </a>
                    </div>
                    {% endif %}
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>My stories and recipes</span></h2>
                    </div>
                </div>
                <div class="row">
                    {% for story in story_list %}
                    <div story-slug="{{story.slug}}" class="col-md-4 ftco-animate">
                        <div class="blog-entry">
                            <a class="img-2">

                                <div class="user-events__edit">
                                    <button type="button" class="edit-event"><i class="fa fa-pencil"
                                            aria-hidden="true"></i></button>
                                    <button type="button" class="delete-event"><i class="fa fa-trash"
                                            aria-hidden="true"></i></button>
                                </div>

                                <img src="{{story.image.url}}" class="img-fluid" alt="Colorlib Template">
                            </a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{story.category.title}}</span><span
                                        class="ml-auto pl-3">{{story.created_at|date:"F d, Y"}}</span>
                                </p>
                                <h3><a href="{{story.get_absolute_url}}">{{story.title}}</a></h3>
                                <p class="mb-0"><a href="{{story.get_absolute_url}}" class="btn btn-black py-2">Read
                                        More <span class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    
                    {% endfor %}

                    {% for recipe in recipes %}
                    <div recipe-slug="{{recipe.slug}}" class="col-md-4 ftco-animate">
                        <div class="blog-entry">
                            <a class="img-2">

                                <div class="user-events__edit">
                                    <button  type="button" class="edit-event"><i class="fa fa-pencil"
                                            aria-hidden="true"></i></button>
                                    <button type="button" class="delete-event"><i class="fa fa-trash"
                                            aria-hidden="true"></i></button>
                                </div>

                                <img src="{{recipe.image.url}}" class="img-fluid" alt="Colorlib Template">
                            </a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{recipe.category.title}}</span><span
                                        class="ml-auto pl-3">{{recipe.created_at|date:"F d, Y"}}</span>
                                </p>
                                <h3><a href="{{recipe.get_absolute_url}}">{{recipe.title}}</a></h3>
                                <p class="mb-0"><a href="{{recipe.get_absolute_url}}" class="btn btn-black py-2">Read
                                        More <span class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>


        </div>
    </div>
</section>
{% endif %}

{% endblock %}

{% block js %}

<script>

    document.querySelectorAll('.edit-event').forEach((element) => {
        element.addEventListener('click', function(){
            const story_slug = element.closest('[story-slug]').getAttribute('story-slug');
            window.location.href = "{% url 'stories:update_story' 'story-slug' %}".replace('story-slug', story_slug)
        })
    });
    document.querySelectorAll('.delete-event').forEach((element) => {
        element.addEventListener('click', function(){
            const delete_story = confirm('Silmek istediyinize eminsinizmi?');
            if (delete_story){
               const story_slug = element.closest('[story-slug]').getAttribute('story-slug');
               //  /update-story/story-slug/
               window.location.href = "{% url 'stories:delete_story' 'story-slug' %}".replace('story-slug', story_slug)
            }
        })
    })

      document.querySelectorAll('.edit-event').forEach((element) => {
        element.addEventListener('click', function(){
            const recipe_slug = element.closest('[recipe-slug]').getAttribute('recipe-slug');
            window.location.href = "{% url 'stories:update_recipe' 'recipe-slug' %}".replace('recipe-slug', recipe_slug)
        })
    });
    document.querySelectorAll('.delete-event').forEach((element) => {
        element.addEventListener('click', function(){
            const delete_recipe = confirm('Silmek istediyinize eminsinizmi?');
            if (delete_recipe){
               const recipe_slug = element.closest('[recipe-slug]').getAttribute('recipe-slug');
               //  /update-story/story-slug/
               window.location.href = "{% url 'stories:delete_recipe' 'recipe-slug' %}".replace('recipe-slug', recipe_slug)
            }
        })
    })
</script>

{% endblock %}