accounts/urls.py
from django.urls import path , re_path
from accounts.views import UserProfile , CreateRegisterView , RegisterUpdateView , CustomLoginView , activate ,\
    CustomPasswordChangeView , ForgetPasswordView , CustomPasswordResetConfirmView
from django.contrib.auth.views import LogoutView

# app_name = "accounts"

app_name = 'user'
urlpatterns = [
    path('user-profile/',UserProfile.as_view(),name = 'user_profile'),
    path('register/', CreateRegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    re_path(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activation'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit_profile/<str:slug>', RegisterUpdateView.as_view(), name='edit_profile'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('forget-password/', ForgetPasswordView.as_view(), name='forget_password'),
    re_path(r'password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

api/urls.py
from django.urls import path
from api.views import recipes_api , recipe,  categories_api, category , SubscriberCreateAPIView
from api.routers import router

urlpatterns = [
    path('recipes/', recipes_api , name = 'recipes'),
    path('recipes/<int:id>/', recipe, name='api_recipe'),
    # path('stories/', stories_api , name = 'stories'),
    # path('stories/<int:id>/', story, name='api_story'),
    # path('stories/?categories=<slug:str>/', story_for_category, name='story_for_category'),
    path('categories/', categories_api , name = 'categories'),
    path('categories/<int:id>/', category, name='api_categories'),
    path('subscribe/', SubscriberCreateAPIView.as_view(), name='subscribe'),
    
] + router.urls

food_stories/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

 

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace='stories')),
    path('user/', include('accounts.urls',namespace='user')),
    path('api/v1.0/', include('api.urls') ),
    path('api/v1.0/auth/', include('accounts.api.urls', namespace='api_account')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path
from stories.views import HomePage , about ,StoryListView , RecipeListView , StoryDetailView , RecipeDetailView , ContactView, \
    CreateStoryView , StoryUpdateView , StoryDeleteView , CreateRecipeView , RecipeUpdateView , RecipeDeleteView , SaveRecipeView, \
    SavedRecipeListView , export_excel_view , SubscriberCreateView


app_name = 'stories'
urlpatterns = [
    path('', HomePage.as_view(), name = 'home'),
    path('about/', about , name = 'about'),
    path('recipes/', RecipeListView.as_view() , name = 'recipes'),
    path('recipes/<str:slug>', RecipeDetailView.as_view(), name='recipe_detail'),
    path('stories/', StoryListView.as_view() , name = 'stories'),
    path('stories/<str:slug>/', StoryDetailView.as_view(), name='story_detail'),
    path('contact/', ContactView.as_view() , name = 'contact'),
    path('create-story',CreateStoryView.as_view(), name = 'create_story'),
    path('create-recipe',CreateRecipeView.as_view(), name = 'create_recipe'),
    path('update-story/<str:slug>/', StoryUpdateView.as_view(), name = 'update_story') ,
    path('delete-story/<str:slug>/', StoryDeleteView.as_view(), name = 'delete_story') ,
    path('update-recipe/<str:slug>/', RecipeUpdateView.as_view(), name = 'update_recipe') ,
    path('delete-recipe/<str:slug>/', RecipeDeleteView.as_view(), name = 'delete_recipe') ,
    path('save-recipe/<int:pk>/', SaveRecipeView.as_view(), name = 'save_recipe') ,
    path('saved-recipes/', SavedRecipeListView.as_view(), name='saved_recipes'),
    path('export/',export_excel_view, name = 'export_excel_view' ),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),
]

stories/forms.py
from django import forms
from stories.models import Contact, Recipe, Story, Category, Tag , Subscriber
from ckeditor.widgets import CKEditorWidget 
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class StoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={
                    'class': 'form-control'
                }))
    tags =  forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={
                    'class': 'form-control',
                }) )
    class Meta:
        model = Story
        fields = ('title', 'category', 'tags', 'long_description', 'image',)
        widgets = {
            'title': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                }),
            'long_description': CKEditorUploadingWidget(),

        }

class RecipeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={
                    'class': 'form-control'
                }))
    tags =  forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={
                    'class': 'form-control',
                }) )
    class Meta:
        model = Recipe
        fields = ('title', 'category', 'tags', 'short_description', 'long_description', 'image',)
        widgets = {
            'title': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                }),
            'short_description': forms.Textarea(attrs={
                    'class': 'form-control',
                    'placeholder': 'Short Description',
                    'rows'  : '5',
                    'cols' : '20',
                }),
            'long_description': CKEditorUploadingWidget(),

        }

class ContactForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=13, initial='+994', min_length=7, widget=forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Phone Number',
                }), help_text='Sizinle elaqeye kecmeyimiz ucun nomre daxil etmeyiniz sertdir!')
    class Meta:
        model = Contact
        fields = (
            'name',
            'email',
            'subject',
            'phone_number',
            'message',
           
        )
        widgets = {
            'name': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Your name',
                }),
            'email': forms.EmailInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Your email',
                }),
            'subject': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Subject',
                }),
            'message': forms.Textarea(attrs={
                    'class': 'form-control',
                    'placeholder': 'Message',
                    'rows': 7,
                    'cols': 30,
                })
        }

    
    def clean(self):
        print('here')
        cleaned_data = super().clean()
        print(cleaned_data)

    # def clean_phone_number(self):
    #     phone_number = self.changed_data.get('phone_number')

class RecipeAdminForm(forms.ModelForm):
    long_description = forms.CharField(widget=CKEditorUploadingWidget())
    class Meta:
        model = Recipe
        fields = '__all__'

class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = (
            'email',
        )

        widgets = {
            'email': forms.EmailInput(attrs={
                'class':  'form-control',
                'placeholder': 'Enter email address',
            })
        }

stories/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.views.generic import ListView , DetailView , CreateView , UpdateView , DeleteView ,TemplateView , View
from stories.models import Category, Recipe , Story , SavedArticle
from stories.forms import ContactForm , StoryForm, RecipeForm , SubscriberForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin , PermissionRequiredMixin
from django.http import HttpResponseForbidden , HttpResponse
from django.core.exceptions import PermissionDenied
import random
from stories.tasks import export_excel


# Create your views here.

# def home(request):
#     recipes = Recipe.objects.all()[:2]
#     stories = Story.objects.all()[:4]
#     context = {
#         'recipes' : recipes,
#         'stories' : stories
#     }
#     return render(request,'index.html',context)

class HomePage(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data( *args, **kwargs)
        if Story.objects.count()>0:
            print('aaaaaaa')
            random_story = random.choice(Story.objects.all())
            context['random_story'] = random_story
        context['recipes'] = Recipe.objects.all().order_by('-show_home_page')[:2]
        context['stories'] = Story.objects.all().order_by('-show_home_page')[:4]
        return context


def about(request):
    return render(request,'about.html')

class StoryListView(ListView):
    model = Story
    template_name = 'stories.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)

class StoryDetailView(DetailView):
    model = Story
    template_name = 'single.html'

# def recipes(request):
#     recipes = Recipe.objects.filter(is_published=True)
#     context = {
#         'recipes': recipes
#     }
#     return render(request, 'recipes.html', context)

class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes.html'
    paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'single.html'

# def stories(request):
#     stories = Story.objects.filter(is_published=True)
#     context = {
#         'stories': stories
#     }
#     return render(request, 'strories.html', context)


# def recipe_detail(request, slug):
#     print(slug)
#     # recipe = Recipe.objects.get(slug=slug)
#     recipe = get_object_or_404(Recipe, slug=slug)
#     context = {
#         'object': recipe
#     }
#     return render(request, 'single.html', context)


class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('stories:home')

    def form_valid(self, form):
        messages.success(self.request, 'Mesajiniz gonderildi!!')
        return super().form_valid(form)

class CreateStoryView(LoginRequiredMixin,CreateView):
    form_class = StoryForm
    template_name = 'create_story.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            if not self.request.user.is_author:
                raise PermissionDenied
            # return HttpResponseForbidden('403 Forbidden')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        story = form.save(commit=False)
        story.author = self.request.user
        story.save()
        return super().form_valid(form)

class CreateRecipeView(LoginRequiredMixin,CreateView):
    form_class = RecipeForm
    template_name = 'create_recipe.html'
    # permission_required = ('stories.add_recipe')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            if not self.request.user.is_author:
                raise PermissionDenied
            # return HttpResponseForbidden('403 Forbidden')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        recipe = form.save(commit=False)
        recipe.author = self.request.user
        recipe.save()
        return super().form_valid(form)

class StoryUpdateView(LoginRequiredMixin,UpdateView):
    form_class = StoryForm
    model = Story
    template_name = 'create_story.html'

class StoryDeleteView(LoginRequiredMixin,DeleteView):
    model = Story
    success_url = reverse_lazy('stories:stories')
    http_method_names = ('get',)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class RecipeUpdateView(LoginRequiredMixin,UpdateView):
    form_class = RecipeForm
    model = Recipe
    template_name = 'create_recipe.html'

class RecipeDeleteView(LoginRequiredMixin,DeleteView):
    model = Recipe
    success_url = reverse_lazy('stories:recipes')
    http_method_names = ('get',)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class SaveRecipeView(View):
    def get(self, *args, **kwargs):
        recipe_id = kwargs.get('pk')
        message = 'Melumat elave edildi'
        recipe = get_object_or_404(Recipe, id=recipe_id)
        
        if self.request.user.is_authenticated:
            save_article, created = SavedArticle.objects.get_or_create(user=self.request.user, recipe=recipe)
            if not created:
                message = 'Melumat evvel elave edilmisdi'
            response = HttpResponse(message)
        else:
            saved_articles = self.request.COOKIES.get('saved_articles', '')
            print('saved_articles', saved_articles)
            if str(recipe_id) not in saved_articles.split(';'):
                saved_articles += str(recipe_id) + ";"
            response = HttpResponse(message)
            response.set_cookie('saved_articles', saved_articles)
        # messages.success(self.request, message)
        return response

class SavedRecipeListView(ListView):
    model = Recipe
    template_name = 'saved_recipes.html'
    paginate_by = 2

    def get_queryset(self, ):
        queryset = []
        if self.request.user.is_authenticated:
            queryset = super().get_queryset()
            user_saved_articles_ids = self.request.user.saved_articles.values_list('id', flat=True)
            return queryset.filter(id__in=user_saved_articles_ids)
        else:
            saved_recipes = self.request.COOKIES.get('saved_articles')
            print(saved_recipes)
            if saved_recipes:
                print('adadadadadadada',saved_recipes)
                saved_recipe_ids = [int(id) for id in saved_recipes.split(';') if id and id != 0]
                queryset = super().get_queryset()
                return queryset.filter(id__in=saved_recipe_ids)
            return queryset
    



# form yaratmadan bele elemek olar , html faylinda {{form}} yazmaqla
# class CreateStoryView(CreateView): 
#     model = Story
#     fields = '__all__'
#     template_name = 'create_story.html'


# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Mesajiniz gonderildi!!')
#             return redirect('/')
#         else:
#             messages.error(request, 'Mesajiniz gonderilmedi')
#     else:
#         form = ContactForm()
#     context = {
#         'form' : form
#     }
#     return render(request, 'contact.html', context)

def export_excel_view(request):
    export_excel.delay()
    return HttpResponse('Export edilir')

class SubscriberCreateView(CreateView):
    form_class = SubscriberForm
    # template_name = None
    http_method_names = ('post',)
    success_url = reverse_lazy('stories:home')

    def get_success_url(self):
        redirect_url = self.request.GET.get('redirect_url', self.success_url)
        return redirect_url

    def form_valid(self, form):
        messages.success(self.request, 'Subscribe oldunuz')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, form.errors)
        redirect_url = self.request.GET.get('redirect_url', self.success_url)
        return redirect(redirect_url) 

stories/templates/includes/footer.html
{% load custom_tags %}
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                        there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    {% category as items %}
                    <ul class="list-unstyled">
                        {% for item in items %}
                        <li><a href="#" class="py-2 d-block">{{item}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain
                                    View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929
                                        210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span
                                        class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                        aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

stories/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
            aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'stories:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'stories:about' %}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{% url 'stories:stories' %}" class="nav-link">Stories</a></li>
                <li class="nav-item"><a href="{% url 'stories:create_story' %}" class="nav-link">Create-Story</a></li>
                <li class="nav-item"><a href="{% url 'stories:create_recipe' %}" class="nav-link">Create-Recipe</a></li>
                <li class="nav-item"><a href="{% url 'user:user_profile' %}" class="nav-link">User-Profile</a></li>
                <li class="nav-item"><a href="{% url 'stories:recipes' %}" class="nav-link">Recipes</a></li>
                <li class="nav-item"><a href="{% url 'stories:saved_recipes' %}" class="nav-link">Saved Articles</a></li>
                <li class="nav-item"><a href="{% url 'stories:contact' %}" class="nav-link">Contact</a></li>
                <li><a href="{% url 'user:register' %}" class="btn btn-black px-3 px-md-4 py-3">Sign Up</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'user:logout' %}" class="btn btn-black px-3 px-md-4 py-3">Log Out</a></li>
                {% else %}
                <li><a href="{% url 'user:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign In</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

stories/templates/includes/subscribers.html
{% load custom_tags %}

{% get_subscriber_form as form %}
<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form  method="POST" class="subscribe-form">
                                <div class="form-group d-flex">
                                    {{form.email}}
                                    {{form.email.help_text}}
                                    <!-- <input type="text" class="form-control" placeholder="Enter email address"> -->
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>